#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.cfh.springboot.pojo
  mapperLocations: classpath:mappers/*.xml

jedis :
  pool :
    host : 119.23.111.185
    port : 6379
    config :
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 100000


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: 19981002520qq
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource


  jedis :
    pool :
      host : 119.23.111.185
      port : 6379
      config :
        maxTotal: 100
        maxIdle: 10
        maxWaitMillis : 100000
