#默认使用配置
spring:
  profiles:
    active: dev

  redis:
   database: 0
   host: 119.23.111.185cd
   port: 6379
   pool:
     max-active: 8
     max-wait: 1
     max-idel: 8
     min-idel: 0
   timeout: 0

#允许访问actuator下的敏感端点
management:
  security:
    enabled: false

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.cfh.springboot.pojo
  mapperLocations: classpath:mappers/*.xml

jedis :
  pool :
    host : 119.23.111.185
    port : 6379
    config :
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 100000

#使用Redis做缓存
#spring:
#  redis:
#   database: 0
#   host: 119.23.111.185
#   port: 6379
#   password: 19981002520qq
#   pool:
#     max-active: 8
#     max-wait: 1
#     max-idel: 8
#     min-idel: 0
#  timeout: 0

#打印dao层的日志
logging:
  level:
    com:
      cfh:
        springboot:
          dao: debug

---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false
    username: root
    password: 19981002520qq
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource


  jedis :
    pool :
      host : 119.23.111.185
      port : 6379
      config :
        maxTotal: 100
        maxIdle: 10
        maxWaitMillis : 100000
